name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17.0.10'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.4"
      - name: Clean build
        run: flutter clean
      - name: Install Dependencies
        run: flutter pub get
      - name: Set Localization
        run: flutter gen-l10n
      - name: Build Apk
        run: flutter build apk
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
            tag_name: v1.0.0  # Replace with your tag name
            release_name: Release v1.0.0  # Replace with your release name
            body: |
              Release of version 1.0.0
            draft: false
            release: false